### PR TITLE
Update fibers dependency

### LINKED ISSUE #173: Support for Node v8+
Using Node `>=v8` fails to build, due to `fibers`.

Either `fibers` should be updated or dropped for adopted `async-await`.

`fibers`

```javascript
plan.local(function(local) {
  local.log('Run build');
  local.exec('gulp build');

  local.log('Copy files to remote hosts');
  var filesToCopy = local.exec('git ls-files', {silent: true});
  // rsync files to all the target's remote hosts
  local.transfer(filesToCopy, '/tmp/' + tmpDir);
});
```

`async-await`

```javascript
plan.local(async (local) =>  {
  local.log('Run build');
  await local.exec('gulp build');

  local.log('Copy files to remote hosts');
  const filesToCopy = await local.exec('git ls-files', {silent: true});
  // rsync files to all the target's remote hosts
  await local.transfer(filesToCopy, '/tmp/' + tmpDir);
});
```

Reference:
#170

### PR DESCRIPTION
**Pull request by renarsvilnis**
CLoses #173 

I'm not familiar with `fibers`. They don't have an updated changelog, but by commits looks more as bugfixes and adding support for newer node versions.

The tests don't fail.

### CODE REVIEW

**Comment by pstadler** [comment]
This is great. Could add Node 8 and 10 targets to .travis.yml and remove everything below 6?

**Comment by pstadler** [comment]
wow, you just did that while I was writing the previous comment 🍻

**Comment by renarsvilnis** [comment]
@pstadler 
Just did it, left node v4 - discounted, but still in maintenance mode. Maybe some users still using in legacy apps.

**Comment by renarsvilnis** [comment]
@pstadler wasn't expecting that fast of a response. 😄 

Don't forget to bump version and publish 🎊

**Comment by pstadler** [comment]
Published. Release notes: https://github.com/pstadler/flightplan/releases/tag/0.6.18

**Pull request merged**
